### PR TITLE
Sync: bring OntoPortal up-to-date with BioPortal releases 6.8.2 and onward

### PR DESCRIPTION
**Pull request by jvendetti**
The purpose of this pull request is to merge BioPortal's master branch with OntoPortal's master branch to bring OntoPortal up-to-date with the latest code from the last several BioPortal releases (versions 6.8.2 through 6.10.5).

To follow are slightly abbreviated release notes for the above-mentioned release range.

### [6.8.2](https://github.com/ncbo/bioportal_web_ui/releases/tag/v6.8.2)

- Added a GitHub Action for deployment workflow
- Style mappings page
- Update linear gradient outdated syntax
- Fixed an issue that prevented the ability to run the application in production and appliance modes locally 
- Fixed an issue that caused 500 errors when clicking on the help icon in top-level landing pages
- Bump tzinfo from 1.2.9 to 1.2.10

### [6.9.0](https://github.com/ncbo/bioportal_web_ui/releases/tag/v6.9.0)

- Add initial support for ontology change requests

### [6.10.0](https://github.com/ncbo/bioportal_web_ui/releases/tag/v6.10.0)

- Upgrade to Ruby 2.7.7
- Upgrade to Rails 6.1.5.1
- Fix an issue that prevents the "Jump To" and "Form Autcomplete" widget demonstrations from working
- Refactor ontology change request code to resolve zeitwerk uninitialized and already initialized constant warnings
- Fix an issue that prevents the "Add synonym proposal" dialog from appearing
- Add simple client-side validation for new and edit project forms
- Fix an issue that prevents a confirmation dialog from appearing when deleting projects
- Fix URI.escape is obsolete warnings
- Fix an issue that prevents numeric ontology ID to acronym resolution
- Remove wild controller route and fix "no route matches" errors
- Modify admin routes not to use the match keyword for single request types
- Remove defunct marginal notes code
- Remove defunct administrative views
- Remove defunct views for the deprecated flexviz visualization tool
- Remove deprecated remote logging functionality
- Remove exhibit route with no controller action
- Refactor code that handles errors responses from the BioPortal REST API
- Fix some RuboCop warnings
- Bump ontologies_api_client from 2.2.0 to 2.2.1
- Bump globalid from 1.0.0 to 1.0.1
- Bump rack from 2.2.4 to 2.2.6.2 

### [6.10.1](https://github.com/ncbo/bioportal_web_ui/releases/tag/v6.10.1)

- Forbid non-AJAX calls to concepts#show
- Move repetitive code in ConceptsController to a before_action filter
- Remove defunct history routes and associated code
- Remove defunct user intention survey code
- Retire old redirects and routes
- Fix "can't modify frozen string" errors in the AnalyticsController
- Enable change request functionality for the GO and UBERON ontologies
- Fix some RuboCop warnings

### [6.10.2](https://github.com/ncbo/bioportal_web_ui/releases/tag/v6.10.2)

- Fixed a "No template found" error that occurs when editing a submission fails
- Fixed a case where the Cancel button on the form for editing a submission fails to navigate back to the ontology summary page
- Fixed an issue that prevented the contents of the "Create new mapping" dialog from displaying properly
- Fixed an issue that prevented the "Create mapping" button from getting styled as intended
- Fixed an issue that prevented detection of the 't' parameter for auto-selecting sub-tabs in the Classes tab
- Updated the documentation link for the virtual appliance
- Updated the copyright year
- Bump rack from 2.2.6.3 to 2.2.6.4
- Bump rack from 2.2.6.2 to 2.2.6.3

### [6.10.3](https://github.com/ncbo/bioportal_web_ui/releases/tag/v6.10.3)

- Added support for the "remove synonym" ontology change request type
- Enabled table sorting for the Mappings tabs within ontologies
- Fixed a JSON::ParserError that occurred on the Admin tab when deleting ontologies
- Fixed an issue that generated 500 errors when invalid ontology IDs are passed to the /mappings/:id URL pattern
- Removed a duplicate root route
- Fixed some RuboCop warnings in the MappingsController

### [6.10.4](https://github.com/ncbo/bioportal_web_ui/releases/tag/v6.10.4)

- Fixed an issue that prevented virtual appliace IDs from appearing on the Admin -> Site Administration tab
- Fixed an issue that prevented virtual appliance users from saving licenses via the Admin -> Licensing tab
- Added support for the "node obsoletion" ontology change request type
- Fixed some RuboCop warnings

### [6.10.5](https://github.com/ncbo/bioportal_web_ui/releases/tag/v6.10.5)

- Fixed an issue that prevented the Cancel button from working on forms for creating / editing projects
- Fixed an issue that caused ActionView::MissingTemplate errors to occur when clicking on the Projects help icon
- Minor refactors in the view / controller code for Projects
- Fixed a broken unit test for the remove synonym change request type

### CODE REVIEW

**Review by syphax-bouazzouni — APPROVED** [review]

**Comment by syphax-bouazzouni** [comment]
Hi @jvendetti , thanks for this detailed PR. I merged it (even if it needs the updated API code also to work) 

I wanted to create a release in this repo, but do you think that we should start again from v1.0.0 or use the latest version of Bioportal v6.10.5

**Comment by syphax-bouazzouni** [comment]
I think v6.10.5 (Bioportal version) is better. (sorry my English is still not to that good)

**Comment by jvendetti** [comment]
I like your English. 😄

I'm not sure what to say about the tag names. Initially I thought it would be good for OntoPortal to have it's own versioning scheme that's independent of BioPortal. However, I'm interested in your point of view about why you think the other way is better. I don't think I feel strongly either way.

And - there's the issue of the Rails Gemfile pointing to an ncbo tag, which isn't so nice:

https://github.com/ontoportal/ontoportal_web_ui/blob/71c732533ccbb3c5d2eac2b0fec59007a092de18/Gemfile#L51

**Comment by jonquet** [comment]
Will vote for staying with the tags from BioPortal (6.8 and so forth OR only the last one 6.10.5).... otherwise we are going to loose the historical relation with BioPortal's code. 
Considering the OntoPortal repo only contains code (master brnach) from BioPortal ... its ok to keep the same tags. 
We will see in the future if they evolve differently.

**Pull request merged**
